version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/hidetake.org
    steps:
      - run:
          name: Install
          command: |
            gcloud components install app-engine-java
      - checkout
      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > "$HOME/gcp-service-account-key.json"
              gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
              gcloud app deploy --project "$GCP_PROJECT_ID" --version "$CIRCLE_BRANCH"
            fi
